--------------------------------------------------------
-- DDL for Sequence
--------------------------------------------------------
CREATE SEQUENCE  "APP"."SEQ_FPG"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  ORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
CREATE SEQUENCE  "APP"."SEQ_ITV"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  ORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
CREATE SEQUENCE  "APP"."SEQ_MAR"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  ORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
CREATE SEQUENCE  "APP"."SEQ_PRD"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  ORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
CREATE SEQUENCE  "APP"."SEQ_VDA"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  ORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;

--------------------------------------------------------
-- DDL for Trigger TG_SEQ_FPG
--------------------------------------------------------
CREATE OR REPLACE NONEDITIONABLE TRIGGER "APP"."TG_SEQ_FPG"
BEFORE INSERT ON forma_pagamento
FOR EACH ROW
BEGIN
  :new.fpg_id := seq_fpg.nextval;
END;

CREATE OR REPLACE NONEDITIONABLE TRIGGER "APP"."TG_SEQ_ITV"
BEFORE INSERT ON item_venda
FOR EACH ROW
BEGIN
  :new.itv_id := seq_itv.nextval;
END;

CREATE OR REPLACE NONEDITIONABLE TRIGGER "APP"."TG_SEQ_MAR" BEFORE
    INSERT ON marca
    FOR EACH ROW
BEGIN
    :new.mar_id := seq_mar.nextval;
END;

CREATE OR REPLACE NONEDITIONABLE TRIGGER "APP"."TG_SEQ_PRD"
BEFORE INSERT ON produto
FOR EACH ROW
BEGIN
  :new.prd_id := seq_prd.nextval;
END;

CREATE OR REPLACE NONEDITIONABLE TRIGGER "APP"."TG_SEQ_VDA"
BEFORE INSERT ON venda
FOR EACH ROW
BEGIN
  :new.vda_id := seq_vda.nextval;
END;