--------------------------------------------------------
-- DDL for Table History
--------------------------------------------------------
CREATE TABLE "APP"."H_FORMA_PAGAMENTO" (
  "HFPG_ID" NUMBER(3,0),
  "HFPG_NOME" VARCHAR2(100),
  "HFPG_DT_ENTRADA" DATE
);

CREATE TABLE "APP"."H_ITEM_VENDA" (
  "HITV_ID" NUMBER(3,0),
  "HITV_VDA_ID" NUMBER(3,0),
  "HITV_PRD_ID" NUMBER(3,0),
  "HITV_QUANTIDADE" NUMBER(8,0),
  "HITV_PRECO_VENDA" NUMBER(8,2),
  "HITV_DT_ENTRADA" DATE
);

CREATE TABLE "APP"."H_MARCA" (	
  "HMAR_ID" NUMBER(3,0), 
  "HMAR_NOME" VARCHAR2(100), 
  "HMAR_DT_ENTRADA" DATE
);

CREATE TABLE "APP"."H_PRODUTO" (
  "HPRD_ID" NUMBER(3,0),
  "HPRD_MAR_ID" NUMBER(3,0),
  "HPRD_NOME" VARCHAR2(100),
  "HPRD_QUANTIDADE" NUMBER(8,0),
  "HPRD_PRECO_CUSTO" NUMBER(8,2),
  "HPRD_PRECO_VENDA" NUMBER(8,2),
  "HPRD_DT_ENTRADA" DATE
);

CREATE TABLE "APP"."VENDA" (
  "VDA_ID" NUMBER(3,0),
  "VDA_DATA_HORA" DATE,
  "VDA_VALOR_TOTAL" NUMBER(10,2)
);