CREATE TABLE "APP"."FORMA_PAGAMENTO" (
    "FPG_ID" NUMBER(3,0),
    "FPG_NOME" VARCHAR2(100)
);

CREATE TABLE "APP"."ITEM_VENDA" (
    "ITV_ID" NUMBER(3,0),
    "ITV_VDA_ID" NUMBER(3,0),
    "ITV_PRD_ID" NUMBER(3,0),
    "ITV_QUANTIDADE" NUMBER(8,0),
    "ITV_PRECO_VENDA" NUMBER(8,2)
);

CREATE TABLE "APP"."MARCA" (
    "MAR_ID" NUMBER(3,0), 
    "MAR_NOME" VARCHAR2(100)
) ;

CREATE TABLE "APP"."PRODUTO" (
    "PRD_ID" NUMBER(3,0),
    "PRD_MAR_ID" NUMBER(3,0),
    "PRD_NOME" VARCHAR2(100),
    "PRD_QUANTIDADE" NUMBER(8,0),
    "PRD_PRECO_CUSTO" NUMBER(8,2),
    "PRD_PRECO_VENDA" NUMBER(8,2)
);

CREATE TABLE "APP"."VENDA" (
    "VDA_ID" NUMBER(3,0),
    "VDA_DATA_HORA" DATE,
    "VDA_VALOR_TOTAL" NUMBER(10,2)
);