alter session set "_ORACLE_SCRIPT" = TRUE;
CREATE USER APP IDENTIFIED BY APP
QUOTA UNLIMITED ON USERS;
GRANT CONNECT, RESOURCE TO APP;

CREATE USER APP_AUDIT IDENTIFIED BY APP_AUDIT
QUOTA UNLIMITED ON USERS;
GRANT CONNECT, RESOURCE TO APP_AUDIT;

GRANT CREATE ANY TRIGGER TO APP_AUDIT;